---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-helm
spec:
  generators:
    - git:
        repoURL: https://github.com/on-clouds/savannah-demo.git
        revision: HEAD
        files:
          - path: argo/**/config-helm.yaml
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      sources:
      - repoURL: '{{ repoURL }}'
        targetRevision: '{{ targetRevision }}'
        chart: '{{ chart }}'
        helm:
          valueFiles:
          - $values/argo/{{ path.basename }}/values.yaml
      - repoURL: https://github.com/on-clouds/savannah-demo 
        targetRevision: HEAD
        path: argo/{{ path.basename }}
      - repoURL: https://github.com/on-clouds/savannah-demo
        targetRevision: HEAD
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ namespace }}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-kustomize
spec:
  generators:
    - git:
        repoURL: https://github.com/on-clouds/savannah-demo.git
        revision: HEAD
        files:
          - path: argo/**/config-kustomize.yaml
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      sources:
      - repoURL: https://github.com/on-clouds/savannah-demo
        targetRevision: HEAD
        path: argo/{{ path.basename }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ namespace }}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
